### ISSUE TITLE
students#index is invalid order in each classroom

### ISSUE THREAD

**Issue by nobuyo** [13J-Programmers/yorusai-entrance#12]
- [x] bug report
- [ ] feature request
- [ ] support request

## Outline

student_id is not sorted in `students/`

and I think, this problem expresses only using postgres(production environment).

## related

http://qiita.com/anoworl/items/af9f12f915b8969ea40d

**Comment by tex2e** [comment]
To solve this, simply, do we just apply `.sort_by(&:student_id)` to students array?

**Comment by nobuyo** [comment]
Let's try.
please commit change and run `git push origin master` and `git push origin master:deploy`
if numbers were sorted on production environment, it turned out good.

**Comment by tex2e** [comment]
Fix this issue by 312fb0454d6abb3698cf9142f69ded79a88ffa61
